# Generated by Django 2.0.3 on 2020-05-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200518_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Menu'),
        ),
    ]
