# Generated by Django 2.0.3 on 2020-05-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200518_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
